package danielandanthony.dungeonsanddragons;

import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.widget.EditText;
import android.content.Intent;
import android.widget.Toast;

/**
 * Put values in the text fields generated by the character sheet button.
 */
public class ActivityCharacterSheet extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        try {
            Intent intent = getIntent();
            Bundle b = intent.getBundleExtra("dndBundle");
            super.onCreate(savedInstanceState);
            setContentView(R.layout.activity_activity_character_sheet);
            CharacterSheet characterSheet = DnD.getCharacterSheet(b.getString("playerName"));
            EditText characterName = (EditText) findViewById(R.id.characterName);
            String playerName = b.getString("playerName");
            characterName.setText(playerName);

            // Plugs in value for armor class.
            EditText aC = (EditText) findViewById(R.id.armorClass);
            int armorClass = DnD.getCharacterSheet(playerName).getarmorClass();
            String armorClassString = String.valueOf(armorClass);
            aC.setText((CharSequence) armorClassString);

            // Plugs in value for constitution.
            EditText constitution = (EditText) findViewById(R.id.con);
            int con = DnD.getCharacterSheet(playerName).getcon();
            String conString = String.valueOf(con);
            constitution.setText((CharSequence) conString);

            // Plugs in value for strength.
            EditText strength = (EditText) findViewById(R.id.str);
            int str = DnD.getCharacterSheet(playerName).getstr();
            String strString = String.valueOf(str);
            strength.setText((CharSequence) strString);

            // Plugs in value for dexterity.
            EditText dexterity = (EditText) findViewById(R.id.dex);
            int dex = DnD.getCharacterSheet(playerName).getdex();
            String dexString = String.valueOf(dex);
            dexterity.setText((CharSequence) dexString);

            // Plugs in value for intellgence.
            EditText intelligence = (EditText) findViewById(R.id.inT);
            int inT = DnD.getCharacterSheet(playerName).getinT();
            String inTString = String.valueOf(inT);
            intelligence.setText((CharSequence) inTString);

            // Plugs in value for wisdom.
            EditText wisdom = (EditText) findViewById(R.id.wis);
            int wis = DnD.getCharacterSheet(playerName).getwis();
            String wisString = String.valueOf(wis);
            wisdom.setText((CharSequence) wisString);

            // Plugs in value for charisma.
            EditText charisma = (EditText) findViewById(R.id.cha);
            int cha = DnD.getCharacterSheet(playerName).getcha();
            String chaString = String.valueOf(cha);
            charisma.setText((CharSequence) chaString);

            // Plugs in value for constitution modifier.
            EditText constitutionMod = (EditText) findViewById(R.id.conMod);
            int conMod = DnD.getCharacterSheet(playerName).getconMod();
            String conModString = String.valueOf(conMod);
            constitutionMod.setText((CharSequence) conModString);

            // Plugs in value for strength modifier.
            EditText strengthMod = (EditText) findViewById(R.id.strMod);
            int strMod = DnD.getCharacterSheet(playerName).getstrMod();
            String strModString = String.valueOf(strMod);
            strengthMod.setText((CharSequence) strModString);

            // Plugs in value for dexterity modifier.
            EditText dexterityMod = (EditText) findViewById(R.id.dexMod);
            int dexMod = DnD.getCharacterSheet(playerName).getdexMod();
            String dexModString = String.valueOf(dexMod);
            dexterityMod.setText((CharSequence) dexModString);

            // Plugs in value for intelligence modifier.
            EditText intelligenceMod = (EditText) findViewById(R.id.intMod);
            int intMod = DnD.getCharacterSheet(playerName).getintMod();
            String intModString = String.valueOf(intMod);
            intelligenceMod.setText((CharSequence) intModString);

            // Plugs in value for wisdom modifier.
            EditText wisdomMod = (EditText) findViewById(R.id.wisMod);
            int wisMod = DnD.getCharacterSheet(playerName).getwisMod();
            String wisModString = String.valueOf(wisMod);
            wisdomMod.setText((CharSequence) wisModString);

            // Plugs in value for charisma modifier.
            EditText charismaMod = (EditText) findViewById(R.id.chaMod);
            int chaMod = DnD.getCharacterSheet(playerName).getchaMod();
            String chaModString = String.valueOf(chaMod);
            charismaMod.setText((CharSequence) chaModString);

            // Plugs in value for sword attack bonus.
            EditText attackBonusSword = (EditText) findViewById(R.id.swordAttackBonus);
            int swordAttackBonus = DnD.getCharacterSheet(playerName).getswordAttackBonus();
            String swordAttackBonusString = String.valueOf(swordAttackBonus);
            attackBonusSword.setText((CharSequence) swordAttackBonusString);

            // Plugs in value for bow attack bonus.
            EditText attackBonusBow = (EditText) findViewById(R.id.bowAttackBonus);
            int bowAttackBonus = DnD.getCharacterSheet(playerName).getbowAttackBonus();
            String bowAttackBonusString = String.valueOf(bowAttackBonus);
            attackBonusBow.setText((CharSequence) bowAttackBonusString);

            // Plugs in value for sword damage bonus.
            EditText damageBonusSword = (EditText) findViewById(R.id.swordDamageBonus);
            int swordDamageBonus = DnD.getCharacterSheet(playerName).getswordDamageBonus();
            String swordDamageBonusString = String.valueOf(swordDamageBonus);
            damageBonusSword.setText((CharSequence) swordDamageBonusString);

            // Plugs in value for bow damage bonus.
            EditText damageBonusBow = (EditText) findViewById(R.id.bowDamageBonus);
            int bowDamageBonus = DnD.getCharacterSheet(playerName).getbowDamageBonus();
            String bowDamageBonusString = String.valueOf(bowDamageBonus);
            damageBonusBow.setText((CharSequence) bowDamageBonusString);

            // Plugs in value for spell damage bonus.
            EditText damageBonusSpell = (EditText) findViewById(R.id.spellDamageBonus);
            int spellDamageBonus = DnD.getCharacterSheet(playerName).getspellDamageBonus();
            String spellDamageBonusString = String.valueOf(spellDamageBonus);
            damageBonusSpell.setText((CharSequence) spellDamageBonusString);

            // Plugs in value for spell healing bonus.
            EditText healingBonus = (EditText) findViewById(R.id.spellHealingBonus);
            int spellHealingBonus = DnD.getCharacterSheet(playerName).getspellHealingBonus();
            String spellHealingBonusString = String.valueOf(spellHealingBonus);
            healingBonus.setText((CharSequence) spellHealingBonusString);

            // Plugs in value for the number of arrows the player has.
            EditText numberOfArrows = (EditText) findViewById(R.id.arrows);
            int arrows = DnD.getCharacterSheet(playerName).getarrows();
            String arrowsString = String.valueOf(arrows);
            numberOfArrows.setText((CharSequence) arrowsString);

            // Plugs in value for how many spells the character can cast per day.
            EditText numberOfSpellsPerDay = (EditText) findViewById(R.id.spellsPerDay);
            int spellsPerDay = DnD.getCharacterSheet(playerName).getspellsPerDay();
            String spellsPerDayString = String.valueOf(spellsPerDay);
            numberOfSpellsPerDay.setText((CharSequence) spellsPerDayString);
        }
        /**
         * If there is no character sheet, instead of crashing, the game will tell you there is no character sheet.
         */
        catch (Exception e ) {
            EditText characterName = (EditText) findViewById(R.id.characterName);
            Intent intent = new Intent(ActivityCharacterSheet.this, DnD.class);
            startActivity(intent);
            Toast.makeText(characterName.getContext(), "Cannot find Character Sheet" , Toast.LENGTH_LONG).show();
        }
    }
}
